// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_steps = "CgkIzqeEhsMMEAIQAg"; // <GPGSID>
        public const string achievement_second_steps = "CgkIzqeEhsMMEAIQDQ"; // <GPGSID>
        public const string achievement_three_of_a_kind = "CgkIzqeEhsMMEAIQCA"; // <GPGSID>
        public const string achievement_royal_flush = "CgkIzqeEhsMMEAIQCw"; // <GPGSID>
        public const string achievement_full_house = "CgkIzqeEhsMMEAIQCg"; // <GPGSID>
        public const string achievement_the_inductivity = "CgkIzqeEhsMMEAIQBw"; // <GPGSID>
        public const string achievement_bachelor_of_inductivity = "CgkIzqeEhsMMEAIQBA"; // <GPGSID>
        public const string achievement_born_lucky = "CgkIzqeEhsMMEAIQDA"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIzqeEhsMMEAIQAw"; // <GPGSID>
        public const string achievement_master_of_inductivity = "CgkIzqeEhsMMEAIQBQ"; // <GPGSID>
        public const string achievement_straight = "CgkIzqeEhsMMEAIQCQ"; // <GPGSID>
        public const string achievement_doctor_of_inductivity = "CgkIzqeEhsMMEAIQBg"; // <GPGSID>

}

