name: Build and Deploy Unity Game to Itch
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: zhukovskygamesstudio/workflows/.github/workflows/itch.yml@main 
    with:
      unity_version: ${{ vars.UNITY_VERSION }}
      itch_io_username: ${{ vars.ITCH_IO_USERNAME }}
      itch_io_game_name: ${{ vars.ITCH_IO_GAME_NAME }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      ITCH_IO_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
